{{- range .Values.kafkaConnectors }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    strimzi.io/cluster: {{ $.Values.clusterName }}
spec:
  class: {{ .class }}
  tasksMax: {{ .taskMax }}
  {{- with .config }}
  config:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
