{{- range .Values.kafkaConnect }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    strimzi.io/use-connector-resources: "true"
    strimzi.io/cluster: {{ $.Values.clusterName }}
  {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  version: {{ .version }}
  image: {{ .image }}
  replicas: {{ .replicas }}
  bootstrapServers: {{ .bootstrapServers }}
  {{- with .tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .authentication }}
  authentication:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .config }}
  config:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
